# Generated by Django 3.0.2 on 2020-01-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login_name', models.CharField(max_length=32, unique=True, verbose_name='user login')),
                ('first_name', models.CharField(max_length=64, verbose_name='First Name User')),
                ('last_name', models.CharField(max_length=64, verbose_name='Last Name User')),
                ('middle_name', models.CharField(max_length=64, verbose_name='Middle Name User')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=32, unique=True, verbose_name='email address')),
                ('address', models.CharField(blank=True, max_length=64, verbose_name='Address')),
                ('birthDay', models.DateField(blank=True, verbose_name='User BirthDay')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
