# Generated by Django 3.0.2 on 2020-01-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birthDay',
            field=models.DateField(blank=True, null=True, verbose_name='User BirthDay'),
        ),
    ]
