# Generated by Django 3.0.2 on 2020-01-08 04:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200108_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='creationData',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registration Data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/%Y/%m/%d/', verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
