# Generated by Django 3.0.2 on 2020-01-08 13:53

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20200108_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[Users.models.validate_phone], verbose_name='Phone Number'),
        ),
    ]
