# Generated by Django 3.0.2 on 2020-01-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Set office name', max_length=32, verbose_name='Office Name')),
                ('short_code', models.CharField(help_text='Set Short code for current office', max_length=5, verbose_name='Short Code')),
                ('address', models.TextField(verbose_name='Place Affress Ofice')),
                ('twoGisCode', models.TextField(help_text='Set 2gis code for curent place', verbose_name='2gis site code')),
            ],
        ),
    ]
