# Generated by Django 3.0.2 on 2020-01-08 14:32

import HomeService.models
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('HomeService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offices',
            name='phone',
            field=models.CharField(default=0, max_length=12, unique=True, validators=[HomeService.models.validate_phone], verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offices',
            name='return_time_start',
            field=models.TimeField(blank=True,default=django.utils.timezone.now, verbose_name='Start Time Return'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offices',
            name='work_time_end',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Work Time End'),
        ),
        migrations.AddField(
            model_name='offices',
            name='work_time_start',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Work Time Start'),
        ),
    ]
