# Generated by Django 3.0.2 on 2020-01-08 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HomeService', '0002_auto_20200108_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offices',
            name='work_time_end',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Work Time End'),
        ),
        migrations.AlterField(
            model_name='offices',
            name='work_time_start',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Work Time Start'),
        ),
    ]
