# Generated by Django 3.0.2 on 2020-01-08 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HomeService', '0003_auto_20200108_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offices',
            name='return_time_start',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='Start Time Return'),
        ),
    ]
