# Generated by Django 3.0.2 on 2020-01-08 15:00

import HomeService.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeService', '0004_auto_20200108_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='offices',
            name='view_on_front',
            field=models.BooleanField(default=False, verbose_name='view on frontend'),
        ),
        migrations.AlterField(
            model_name='offices',
            name='address',
            field=models.TextField(blank=True, verbose_name='Place Affress Ofice'),
        ),
        migrations.AlterField(
            model_name='offices',
            name='phone',
            field=models.CharField(blank=True, max_length=12, unique=True, validators=[HomeService.models.validate_phone], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='offices',
            name='twoGisCode',
            field=models.TextField(blank=True, help_text='Set 2gis code for curent place', verbose_name='2gis site code'),
        ),
    ]
