# Generated by Django 3.0.2 on 2020-01-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeService', '0005_auto_20200108_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name Work Type')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='Description for work type')),
            ],
            options={
                'verbose_name': 'Work Type',
                'verbose_name_plural': 'Works Type',
            },
        ),
        migrations.AlterModelOptions(
            name='offices',
            options={'verbose_name': 'Ofice', 'verbose_name_plural': 'Ofices'},
        ),
    ]
