# Generated by Django 3.0.2 on 2020-01-08 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeService', '0006_auto_20200108_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Work Name')),
                ('unit', models.CharField(choices=[('1', 'кв.м.'), ('2', 'шт.')], max_length=10, verbose_name='unit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('master_percent', models.PositiveSmallIntegerField(max_length=100, verbose_name='master Percent')),
                ('admin_percent', models.PositiveSmallIntegerField(max_length=100, verbose_name='Admin Percent')),
                ('workType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeService.WorkType')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works List',
            },
        ),
    ]
