# Generated by Django 3.0.2 on 2020-01-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeService', '0007_workslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workslist',
            name='admin_percent',
            field=models.PositiveSmallIntegerField(verbose_name='Admin Percent'),
        ),
        migrations.AlterField(
            model_name='workslist',
            name='master_percent',
            field=models.PositiveSmallIntegerField(verbose_name='master Percent'),
        ),
    ]
