# Generated by Django 3.0.2 on 2020-01-09 05:28

import HomeService.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeService', '0008_auto_20200108_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='First Name User')),
                ('last_name', models.CharField(max_length=64, verbose_name='Last Name User')),
                ('middle_name', models.CharField(max_length=64, verbose_name='Middle Name User')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[HomeService.models.validate_phone], verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=32, unique=True, verbose_name='email address')),
                ('address', models.CharField(blank=True, max_length=64, verbose_name='Address')),
                ('birthDay', models.DateField(blank=True, null=True, verbose_name='User BirthDay')),
                ('creationData', models.DateTimeField(auto_now_add=True, verbose_name='Registration Data')),
                ('lastAction', models.DateTimeField(blank=True, verbose_name='Last Action Data')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
