# Generated by Django 3.0.2 on 2020-01-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeService', '0009_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='lastAction',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Action Data'),
        ),
    ]
