# Generated by Django 3.0.2 on 2020-01-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeService', '0010_auto_20200109_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(blank=True, max_length=32, unique=True, verbose_name='email address'),
        ),
    ]
